# Generated by Django 3.1.7 on 2021-05-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_activation_public_key_ecc'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='private_key_ecc',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
