# Generated by Django 3.1.7 on 2021-05-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210522_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='private_key_ecc',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='activation',
            name='public_key_ecc',
            field=models.CharField(max_length=300),
        ),
    ]
